spring.application.name=userService
server.port=8080
#spring.data.mongodb.uri=mongodb://mongoDb:27017/customer

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://newbichitra.c9mmoa0cgfgf.eu-north-1.rds.amazonaws.com:5432/customer_service
spring.datasource.username=postgres
spring.datasource.password=L05cE16472ZWKX

# Hibernate Configuration
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.release_mode=auto
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
AUTH.SECRET.KEY=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437






#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

## Connection Pool Configuration (Optional, using HikariCP by default)
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=20000

